import React, { useReducer, useState } from "react";
import Head from "next/head";
import { TextProvider, useText } from "../context";
import Navigations from "../components/Navigations";
import AccessBar from "../components/AccessBar";
import ShowText from "../components/ShowText";
import InputForm from "../components/InputForm";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import AppNew from "../components/AppNew";


const Index = () => {
  
  const [showPopUp, setshowPopUp] = useState(false);
  const [headerType, setheaderType] = useState("div");
  return (
    <div>
      <Head>
        <title>NotionLike Text Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigations />
        <div className="max-w-2xl m-auto">
          <AccessBar />
          <h1
            id="header"
            className="text-4xl border-b-2 p-2 mt-8 mb-5 font-bold"
          >
            Front-end developer test project
          </h1>
          <p className="text-gray-600">
            Your goal is to make a page that looks exactly like this one, and
            has the ability to create H1 text simply by typing / then, typing
            text, and hitting enter.
          </p>
          <TextProvider>
            <ShowText />
            <InputForm
              allowable={{
                showPopUp: showPopUp,
                setshowPopUp: setshowPopUp,
                headerType: headerType,
                setheaderType: setheaderType,
              }}
            />
          </TextProvider>

          <Provider store={store}>
              <AppNew />
          </Provider>
        </div>
      </main>
    </div>
  );
};

export default Index;
